# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy
on:
    push:
        branches:
            - master
        paths:
            - '**.ts'
            - '**.js'
            - '**.json'
            - '**.yml'
jobs:
    updateLayouts:
        runs-on: ubuntu-18.04
        if: github.repository_owner == 'ThemezerNX'
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Install Deps
              run: yarn
            - name: Compile Script
              run: yarn run deploy:compile
            - name: Update Layouts
              env:
                  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
                  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
              run: yarn run deploy
            - name: Prettify
              run: yarn run pretty
            - name: Push changes
              run: |
                  git config user.name 'ThemezerNX'
                  git config user.email 'ThemezerNX@users.noreply.github.com'
                  git remote set-url origin https://ThemezerNX:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
                  if [[ `git status --porcelain --untracked-files=no` ]]; then
                    git commit -am "Prettify & Automated UUID generation"
                    git push
                  fi
            - name: Updating overlays in storage
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSHHOST }}
                  username: ${{ secrets.SSHUSERNAME }}
                  password: ${{ secrets.SSHPASSWORD }}
                  script: |
                      cd /home/themezer/Layouts
                      git reset --hard
                      git pull
                      yarn
                      yarn run deploy:compile
                      yarn run symlink
                      find . -xtype l -delete
